# This credentials secret allows cloudflared to authenticate itself
# to the Cloudflare infrastructure.
{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.secretname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  credentials.json: |-
    {
      "AccountTag": {{ .Values.cloudflare.account | quote }},
      "TunnelID": {{ .Values.cloudflare.tunnelId | quote }},
      "TunnelName": {{ .Values.cloudflare.tunnelName | quote }},
      "TunnelSecret": {{ .Values.cloudflare.secret | quote }}
    }
{{- end -}}